/// Flutter icons Herodyicons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Herodyicons
///      fonts:
///       - asset: fonts/Herodyicons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Herodyicons {
  Herodyicons._();

  static const _kFontFam = 'Herodyicons';
  static const _kFontPkg = null;

  static const IconData projects =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gigs =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData internships =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telecallings =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
